### ISSUE TITLE
Getting 404 errors

### ISSUE THREAD

**Issue by ghost** [jkiddo/gmusic.api#15]
I'm getting 404 errors thrown by any call of dispatchGet()

I'm using a logged in api client.

Any thoughts?  Is there known breakage right now?

**Comment by vl0w** [comment]
Same things happens when I try to run the main method of ```APIexample``` as soon as it get's to 
line 70 (``` api.downloadSong(_song) ```)

**Comment by correaj418** [comment]
I've got the same problem as @vl0w

**Comment by jkiddo** [comment]
And you guys having trouble are already signed up with a Google Music account?

**Comment by correaj418** [comment]
I'm already signed up to Google Music. I'm not having any trouble logging in through the official app or through your API.

**Comment by jkiddo** [comment]
@correaj418 could you provide a stacktrace and the url of the song that you are trying to download?

**Comment by jkauflin** [comment]
I logged in successfully, but got this error just trying to get the playlists:

Line 64            api.login(username, password);            
Line 65
Line 66            Playlists playlists = api.getAllPlaylists();

Thu Feb 05 16:28:56 EST 2015
java.lang.IllegalStateException: Statuscode 404 not supported
	at gmusic.api.comm.HttpUrlConnector.dispatchPost(HttpUrlConnector.java:90)
	at gmusic.api.impl.GoogleMusicAPI.getPlaylistAssist(GoogleMusicAPI.java:249)
	at gmusic.api.impl.GoogleMusicAPI.getAllPlaylists(GoogleMusicAPI.java:195)
	at test.JJKAPITest.main(JJKAPITest.java:66)
Thu Feb 05 16:28:59 EST 2015

**Comment by jkiddo** [comment]
@jkauflin Is it only the playlist part that does not work for you?

**Comment by jkauflin** [comment]
I was just testing the library for the first time.  This was the first thing I tried - just gettings the playlists.  Should I try something else?

**Comment by alex-ayala** [comment]
@jkiddo I'm getting the same issue in that getAllPlaylists throws a 404. Looking at the original Python version of this, it seems that the URL we re querying might have changed. Or does getAllPlaylists work for you? I am using the unit test apiexample file.

**Comment by jkiddo** [comment]
@alex-ayala and @jkauflin nope, you're right. It does not work for me either to call getAllPlaylists. Its been a while since I've looked at the python implementation. Actually, my port was based on a .NET implementation. I would be happy to see any pull requests to this project - especially if someone would look through the python implementation and update this port.

**Comment by jkiddo** [comment]
I really need help to maintain this API. Does anyone of you guys have the time to help me out and get it up to date? It still seems like Simon Weber is keeping his implementation in Python up-to-date so apparently all the dirty work has already been done.

**Comment by jkauflin** [comment]
If I get some time I'll take a look.  Thanks for getting this going in the first place.

**Comment by jkiddo** [comment]
Simons repo can be found at https://github.com/simon-weber/Unofficial-Google-Music-API

**Comment by jkauflin** [comment]
Yes, I'm looking at the newest updates there (and learning a bit about Python which I did not know).
